/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Cloud' at '30/03/15 00:53' with Gradle 2.3
 *
 * @author Cloud, @date 30/03/15 00:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
